# Generated by Django 3.1.3 on 2021-04-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20210410_0730'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
